version: '3.9'

services:
  wordpress:
    ports:
      - "8089:80"
    volumes:
      - /home/bjaskulski/Repos/shopmagic-next:/var/www/html/wp-content/plugins/shopmagic-for-woocommerce:rw
#       - /home/bjaskulski/Repos/WPDesk/shopmagic-for-woocommerce:/var/www/html/wp-content/plugins/shopmagic-for-woocommerce:rw
