version: '3.9'

services:
  wordpress:
    image: bjaskulski/wordpress:6.1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    init: true
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: db
      WORDPRESS_DB_PASSWORD: db
      WORDPRESS_DB_NAME: db
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define("WP_DEBUG_LOG", "wp-content/debug/debug.log");
        define("SCRIPT_DEBUG", true);
        define("WP_DEFAULT_THEME", "storefront");
        define("ALTERNATE_WP_CRON", true);
        define("WP_ENVIRONMENT_TYPE", 'development');
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
    volumes:
      - ./90-xdebug.ini:/usr/local/etc/php/conf.d/90-xdebug.ini:cached
      - ./debug:/var/www/html/wp-content/debug

  mysql:
    image: mysql:5.7
    init: true
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
